import { apiClient } from '../api/client';

export const warehouseService = {
  getWarehouses: (params) => apiClient.get('/warehouses', { params }).then(res => res.data.data || res.data),
  createWarehouse: (data) => apiClient.post('/warehouses', data).then(res => res.data.data || res.data),
  getWarehouseById: (id) => apiClient.get(`/warehouses/${id}`).then(res => res.data.data || res.data),
  updateWarehouse: (id, data) => apiClient.put(`/warehouses/${id}`, data).then(res => res.data.data || res.data),
  deleteWarehouse: (id) => apiClient.delete(`/warehouses/${id}`).then(res => res.data.data || res.data),
  getWarehouseStock: (id) => apiClient.get(`/warehouses/${id}/stock`).then(res => res.data.data || res.data),
  getWarehouseProducts: (id) => apiClient.get(`/warehouses/${id}/products`).then(res => res.data.data || res.data),
  transferStock: (id, data) => apiClient.post(`/warehouses/${id}/transfers`, data).then(res => res.data.data || res.data),
  logInward: (id, data) => apiClient.post(`/warehouses/${id}/inward`, data).then(res => res.data.data || res.data),
  logOutward: (id, data) => apiClient.post(`/warehouses/${id}/outward`, data).then(res => res.data.data || res.data),
  getWarehouseMovements: (id) => apiClient.get(`/warehouses/${id}/movements`).then(res => res.data.data || res.data),
  getWarehouseHistory: (id) => apiClient.get(`/warehouses/${id}/history`).then(res => res.data.data || res.data),
  getWarehouseTimeline: (id) => apiClient.get(`/warehouses/${id}/timeline`).then(res => res.data.data || res.data),
  addStaff: (id, data) => apiClient.post(`/warehouses/${id}/staff`, data).then(res => res.data.data || res.data),
  getStaff: (id) => apiClient.get(`/warehouses/${id}/staff`).then(res => res.data.data || res.data),
  addZone: (id, data) => apiClient.post(`/warehouses/${id}/zones`, data).then(res => res.data.data || res.data),
  getZones: (id) => apiClient.get(`/warehouses/${id}/zones`).then(res => res.data.data || res.data),
  updateZone: (id, zoneId, data) => apiClient.put(`/warehouses/${id}/zones/${zoneId}`, data).then(res => res.data.data || res.data),
  deleteZone: (id, zoneId) => apiClient.delete(`/warehouses/${id}/zones/${zoneId}`).then(res => res.data.data || res.data),
  addRack: (id, data) => apiClient.post(`/warehouses/${id}/racks`, data).then(res => res.data.data || res.data),
  getRacks: (id) => apiClient.get(`/warehouses/${id}/racks`).then(res => res.data.data || res.data),
  updateRack: (id, rackId, data) => apiClient.put(`/warehouses/${id}/racks/${rackId}`, data).then(res => res.data.data || res.data),
  deleteRack: (id, rackId) => apiClient.delete(`/warehouses/${id}/racks/${rackId}`).then(res => res.data.data || res.data),
  addBin: (id, data) => apiClient.post(`/warehouses/${id}/bins`, data).then(res => res.data.data || res.data),
  getBins: (id) => apiClient.get(`/warehouses/${id}/bins`).then(res => res.data.data || res.data),
  updateBin: (id, binId, data) => apiClient.put(`/warehouses/${id}/bins/${binId}`, data).then(res => res.data.data || res.data),
  deleteBin: (id, binId) => apiClient.delete(`/warehouses/${id}/bins/${binId}`).then(res => res.data.data || res.data),
  getValuation: (id) => apiClient.get(`/warehouses/${id}/valuation`).then(res => res.data.data || res.data),
  getCapacity: (id) => apiClient.get(`/warehouses/${id}/capacity`).then(res => res.data.data || res.data),
  getLowStock: (id) => apiClient.get(`/warehouses/${id}/low-stock`).then(res => res.data.data || res.data),
  getOutOfStock: (id) => apiClient.get(`/warehouses/${id}/out-of-stock`).then(res => res.data.data || res.data),
  getDamagedStock: (id) => apiClient.get(`/warehouses/${id}/damaged-stock`).then(res => res.data.data || res.data),
  getExpiryStock: (id) => apiClient.get(`/warehouses/${id}/expiry-stock`).then(res => res.data.data || res.data),
  addAdjustment: (id, data) => apiClient.post(`/warehouses/${id}/adjustment`, data).then(res => res.data.data || res.data),
  getAdjustments: (id) => apiClient.get(`/warehouses/${id}/adjustments`).then(res => res.data.data || res.data),
  addDocument: (id, data) => apiClient.post(`/warehouses/${id}/documents`, data).then(res => res.data.data || res.data),
  getDocuments: (id) => apiClient.get(`/warehouses/${id}/documents`).then(res => res.data.data || res.data),
  addNote: (id, data) => apiClient.post(`/warehouses/${id}/notes`, data).then(res => res.data.data || res.data),
  getNotes: (id) => apiClient.get(`/warehouses/${id}/notes`).then(res => res.data.data || res.data),
  getAnalytics: (id) => apiClient.get(`/warehouses/${id}/analytics`).then(res => res.data.data || res.data),
  blockWarehouse: (id) => apiClient.post(`/warehouses/${id}/block`).then(res => res.data.data || res.data),
  unblockWarehouse: (id) => apiClient.post(`/warehouses/${id}/unblock`).then(res => res.data.data || res.data),
  getDashboardSummary: () => apiClient.get('/warehouses/dashboard-summary').then(res => res.data.data || res.data)
};
