import React from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { CheckCircle2, XCircle, MapPin, Calendar, Clock, Building, User, ArrowLeft, ShieldCheck, Loader2 } from 'lucide-react';
import { meetupsService } from '../services';

const VerifyPass = () => {
    const [searchParams] = useSearchParams();
    const navigate = useNavigate();
    
    const meetupId = searchParams.get('m');
    const userId = searchParams.get('u');

    const { data: verificationData, isLoading, error, isError } = useQuery({
        queryKey: ['verify-pass-reg', meetupId, userId],
        queryFn: () => meetupsService.verifyRegistration(meetupId, userId),
        enabled: !!meetupId && !!userId,
        retry: false,
        refetchOnWindowFocus: false
    });

    const reg = verificationData?.data || verificationData;

    const formatDate = (dateStr) => {
        if (!dateStr) return 'N/A';
        try {
            return new Date(dateStr).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
        } catch {
            return dateStr;
        }
    };

    return (
        <div style={{ minHeight: '100vh', background: '#F0F9F4', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '1.5rem', fontFamily: "'Inter', sans-serif" }}>
            
            {/* Branding Header */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', color: '#064E3B', fontWeight: '950', letterSpacing: '0.05em', marginBottom: '2rem', textTransform: 'uppercase', fontSize: '0.9rem' }}>
                <ShieldCheck size={20} />
                <span>Cliks Secure Validation</span>
            </div>

            <div style={{ 
                background: 'white', 
                borderRadius: '28px', 
                width: '100%', 
                maxWidth: '400px', 
                padding: '2.5rem 2rem', 
                boxShadow: '0 20px 40px rgba(6, 78, 59, 0.08)', 
                border: '1px solid #E2E8F0',
                textAlign: 'center' 
            }}>
                
                {isLoading ? (
                    <div style={{ padding: '4rem 0' }}>
                        <Loader2 className="animate-spin" size={48} style={{ color: '#059669', margin: '0 auto 1rem' }} />
                        <h3 style={{ fontSize: '1.2rem', fontWeight: '850', color: '#1E293B', margin: 0 }}>Querying Registry...</h3>
                        <p style={{ color: '#64748B', fontSize: '0.9rem', marginTop: '0.5rem' }}>Scanning relational RSVP records</p>
                    </div>
                ) : isError || !reg ? (
                    <div style={{ animation: 'fadeIn 0.4s ease' }}>
                        <div style={{ 
                            width: '72px', height: '72px', borderRadius: '50%', background: '#FEF2F2', color: '#DC2626', 
                            display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1.5rem' 
                        }}>
                            <XCircle size={40} />
                        </div>
                        <h2 style={{ fontSize: '1.5rem', fontWeight: '900', color: '#991B1B', marginBottom: '0.5rem' }}>Invalid Pass</h2>
                        <p style={{ color: '#64748B', fontSize: '0.95rem', fontWeight: '500', margin: '0 0 2rem 0', lineHeight: 1.5 }}>
                            {error?.response?.data?.message || "This QR Code does not match any valid attendee reservation on record."}
                        </p>
                        
                        <div style={{ background: '#FFFBEB', border: '1px solid #FEF3C7', color: '#D97706', borderRadius: '12px', padding: '1rem', fontSize: '0.8rem', fontWeight: '650', display: 'flex', gap: '6px', textAlign: 'left', marginBottom: '2rem' }}>
                            ⚠️ Security Notice: Only official passes generated by Cliks Business are recognized at check-in.
                        </div>
                    </div>
                ) : (
                    <div style={{ animation: 'fadeIn 0.4s ease' }}>
                        {/* Success Dynamic Anchor */}
                        <div style={{ 
                            width: '80px', height: '80px', borderRadius: '50%', background: '#DCF2E4', color: '#059669', 
                            display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1.5rem',
                            boxShadow: '0 0 0 8px #ECFDF5'
                        }}>
                            <CheckCircle2 size={44} strokeWidth={2.5} />
                        </div>
                        <span style={{ background: '#DCF2E4', color: '#047857', padding: '0.4rem 0.85rem', borderRadius: '100px', fontSize: '0.7rem', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                            Entry Confirmed
                        </span>
                        <h2 style={{ fontSize: '1.75rem', fontWeight: '950', color: '#064E3B', marginTop: '0.75rem', marginBottom: '1.5rem', letterSpacing: '-0.02em' }}>
                            Pass Validated
                        </h2>

                        {/* Details Framework */}
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', textAlign: 'left', background: '#F8FAFC', padding: '1.5rem', borderRadius: '20px', border: '1px solid #F1F5F9', marginBottom: '1.5rem' }}>
                            <div>
                                <span style={{ display: 'block', fontSize: '0.65rem', color: '#94A3B8', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.25rem' }}>Attendee Name</span>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.95rem', fontWeight: '850', color: '#1E293B' }}>
                                    <User size={15} style={{ color: '#059669' }} />
                                    {reg.username || 'Cliks Builder'}
                                </div>
                            </div>
                            {reg.business_name && (
                                <div>
                                    <span style={{ display: 'block', fontSize: '0.65rem', color: '#94A3B8', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.25rem' }}>Registered Company</span>
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '0.9rem', fontWeight: '750', color: '#475569' }}>
                                        <Building size={14} style={{ color: '#64748B' }} />
                                        {reg.business_name}
                                    </div>
                                </div>
                            )}
                            <div style={{ height: '1px', background: '#E2E8F0', margin: '0.25rem 0' }} />
                            <div>
                                <span style={{ display: 'block', fontSize: '0.65rem', color: '#94A3B8', fontWeight: '800', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '0.25rem' }}>Meetup Event</span>
                                <div style={{ fontSize: '1rem', fontWeight: '900', color: '#0F172A', marginBottom: '0.5rem' }}>{reg.title}</div>
                                <div style={{ display: 'flex', gap: '1rem', fontSize: '0.8rem', color: '#64748B', fontWeight: '600' }}>
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><Calendar size={13} />{formatDate(reg.date)}</div>
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><Clock size={13} />{reg.time}</div>
                                </div>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.8rem', color: '#64748B', fontWeight: '600', marginTop: '0.35rem' }}>
                                    <MapPin size={13} /> {reg.location}
                                </div>
                            </div>
                        </div>

                        <div style={{ fontSize: '0.65rem', color: '#94A3B8', fontWeight: '700', letterSpacing: '0.05em' }}>
                            VALIDATION ID: REG-TXN-{reg.id || meetupId}-{userId}
                        </div>
                    </div>
                )}

                <button 
                    onClick={() => navigate('/')}
                    style={{ 
                        width: '100%', marginTop: '2rem', padding: '1rem', borderRadius: '14px', 
                        border: 'none', background: '#064E3B', color: 'white', fontWeight: '850', 
                        fontSize: '0.95rem', cursor: 'pointer', display: 'flex', alignItems: 'center', 
                        justifyContent: 'center', gap: '6px', boxShadow: '0 8px 20px rgba(6, 78, 59, 0.15)'
                    }}
                >
                    <ArrowLeft size={16} /> Exit to Portal
                </button>
            </div>
        </div>
    );
};

export default VerifyPass;
