import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const normalizeKey = (k) => {
    if (!k || typeof k !== 'string') return '';
    const keyMap = {
        'Dashboard': 'dashboard',
        'Generate Invoice': 'generateInvoice',
        '+ Generate Invoice': 'generateInvoice',
        'Finance': 'finance',
        'Accounting': 'accounting',
        'Expenses': 'expenses',
        'Tax': 'tax',
        'Sales': 'sales',
        'Sales Invoice': 'salesInvoice',
        'Customers': 'customers',
        'Purchases': 'purchases',
        'Purchase Invoice': 'purchaseInvoice',
        'Suppliers': 'suppliers',
        'Inventory': 'inventory',
        'Products': 'products',
        'Stock': 'stockItems',
        'Warehouse': 'warehouses',
        'Warehouses / Godowns': 'warehouses',
        'HR': 'hr',
        'Staff': 'staff',
        'Attendance': 'attendance',
        'Payroll': 'payroll',
        'POS Billing': 'posBilling',
        'Reports': 'reports',
        'Barcode Gen': 'barcodeGen',
        'Marketing': 'marketing',
        'Settings': 'settings',
        'Help & Support': 'helpSupport',
        'Storage': 'storage',
        'Refer & Earn': 'referEarn',
        'Manage Plan': 'managePlan',
        'People': 'people',
        'Wallet': 'wallet',
        'Transaction': 'transaction',
        'Segregation': 'segregation',
        'Split & Collect': 'splitCollect',
        'Planner': 'planner',
        'Rewards & Offers': 'rewardsOffers',
        'BETA Club': 'betaClub',
        'Trading docs': 'tradingDocs',
        'Add Money': 'addMoney',
        'Books': 'books',
        'Payments': 'payments',
        'Social': 'social',
        'Unlock special platform deals, discounts, and premium tier unlocks.': 'rewardsSubtitle',
        'Active Rewards Plan': 'activeRewardsPlan',
        'Grow Your Business, Collect Premium Perks': 'growBusinessPerks',
        'Total Wallet Points': 'totalWalletPoints',
        'Convert to Wallet': 'convertToWallet',
        'Exclusive Offers & Boosters': 'exclusiveOffersBoosters',
        'Updated Hourly': 'updatedHourly',
        'Starter Wallet Load Reward': 'starterWalletReward',
        'Silver Wallet Load Reward': 'silverWalletReward',
        'Gold Wallet Load Reward': 'goldWalletReward',
        'Platinum Wallet Load Reward': 'platinumWalletReward',
        'Load Wallet Now': 'loadWalletNow',
        'Load Wallet Now →': 'loadWalletNow',
        'Business Overview': 'businessOverview',
        'Monitor your enterprise performance and operations.': 'monitorPerformance',
        'Customise': 'customise',
        'Total Sales Revenue': 'totalSalesRevenue',
        'Total Purchases': 'totalPurchases',
        'Total Expenses': 'totalExpenses',
        'Est. Net Profit': 'estNetProfit',
        'Quick Action Center': 'quickActionCenter',
        'New Invoice': 'newInvoice',
        'Sales Orders': 'salesOrders',
        'Add Product': 'addProduct',
        'Add Expense': 'addExpense',
        'Add Customer': 'addCustomer',
        'New Purchase PO': 'newPurchasePo',
        'Staff Claim': 'staffClaim',
        'Onboard Staff': 'onboardStaff',
        'GST Records': 'gstRecords',
        'Marketing Hub': 'marketingHub',
        'FIN-PRO Audit Hub': 'caAuditHub',
        'Purchase Bills': 'purchaseBills',
        'New Purchase Bill': 'newPurchaseBill',
        'Purchase Returns': 'purchaseReturns',
        'New Purchase Return': 'newPurchaseReturn',
        'Sales Returns': 'salesReturns',
        'Stock Management': 'stockManagement',
        'Godown/Warehouse': 'godownWarehouse',
        'Barcode Generator': 'barcodeGenerator',
        'Payments Ledger': 'paymentsLedger',
        'Company Wallet': 'companyWallet',
        'Loyalty Rewards': 'loyaltyRewards',
        'Staff Payroll': 'staffPayroll',
        'Double Entry Accounting': 'doubleEntryAccounting',
        'Delivery Challan': 'deliveryChallan',
        'Theme Customization': 'themeCustomization',
        'Manage Shortcuts': 'manageShortcuts',
        'Sales Performance': 'salesPerformance',
        'Finance Distribution': 'financeDistribution'
    };
    if (keyMap[k]) return keyMap[k];
    return k.trim()
        .replace(/[^a-zA-Z0-9 ]/g, '')
        .replace(/(?:^\w|[A-Z]|\b\w)/g, (word, index) => index === 0 ? word.toLowerCase() : word.toUpperCase())
        .replace(/\s+/g, '');
};

const translations = {
    'EN-US': {
        books: 'Books',
        payments: 'Payments',
        social: 'Social',

        dashboard: 'Dashboard',
        generateInvoice: 'Generate Invoice',
        finance: 'Finance',
        accounting: 'Accounting',
        expenses: 'Expenses',
        tax: 'Tax',
        sales: 'Sales',
        salesInvoice: 'Sales Invoice',
        customers: 'Customers',
        purchases: 'Purchases',
        purchaseInvoice: 'Purchase Invoice',
        suppliers: 'Suppliers',
        inventory: 'Inventory',
        products: 'Products',
        stockItems: 'Stock Items',
        warehouses: 'Warehouses',
        hr: 'HR',
        staff: 'Staff',
        attendance: 'Attendance',
        payroll: 'Payroll',
        posBilling: 'POS Billing',
        reports: 'Reports',
        barcodeGen: 'Barcode Gen',
        marketing: 'Marketing',
        settings: 'Settings',
        helpSupport: 'Help & Support',
        customization: 'Customization',
        advancedEngineConfig: 'Advanced Engine Configuration',
        back: 'BACK',
        deployConfig: 'DEPLOY CONFIG',
        storage: 'Storage',
        referEarn: 'Refer & Earn',
        managePlan: 'Manage Plan',
        people: 'People',
        wallet: 'Wallet',
        transaction: 'Transaction',
        segregation: 'Segregation',
        splitCollect: 'Split & Collect',
        planner: 'Planner',
        rewardsOffers: 'Rewards & Offers',
        rewardsSubtitle: 'Unlock special platform deals, discounts, and premium tier unlocks.',
        activeRewardsPlan: 'Active Rewards Plan',
        growBusinessPerks: 'Grow Your Business, Collect Premium Perks',
        rewardsDescription: 'Complete milestones, scale your active ledger, and transact consistently to stack loyalty points and unlock deep discounts across your workspace subscriptions.',
        totalWalletPoints: 'Total Wallet Points',
        convertToWallet: 'Convert to Wallet',
        exclusiveOffersBoosters: 'Exclusive Offers & Boosters',
        updatedHourly: 'Updated Hourly',
        starterWalletReward: 'Starter Wallet Load Reward',
        silverWalletReward: 'Silver Wallet Load Reward',
        goldWalletReward: 'Gold Wallet Load Reward',
        platinumWalletReward: 'Platinum Wallet Load Reward',
        loadWalletNow: 'Load Wallet Now →',
        businessOverview: 'Business Overview',
        monitorPerformance: 'Monitor your enterprise performance and operations.',
        customise: 'Customise',
        totalSalesRevenue: 'Total Sales Revenue',
        totalPurchases: 'Total Purchases',
        totalExpenses: 'Total Expenses',
        estNetProfit: 'Est. Net Profit',
        quickActionCenter: 'Quick Action Center',
        newInvoice: 'New Invoice',
        salesOrders: 'Sales Orders',
        addProduct: 'Add Product',
        addExpense: 'Add Expense',
        addCustomer: 'Add Customer',
        newPurchasePo: 'New Purchase PO',
        staffClaim: 'Staff Claim',
        onboardStaff: 'Onboard Staff',
        gstRecords: 'GST Records',
        marketingHub: 'Marketing Hub',
        caAuditHub: 'FIN-PRO Audit Hub',
        purchaseBills: 'Purchase Bills',
        newPurchaseBill: 'New Purchase Bill',
        purchaseReturns: 'Purchase Returns',
        newPurchaseReturn: 'New Purchase Return',
        salesReturns: 'Sales Returns',
        stockManagement: 'Stock Management',
        godownWarehouse: 'Godown/Warehouse',
        barcodeGenerator: 'Barcode Generator',
        paymentsLedger: 'Payments Ledger',
        companyWallet: 'Company Wallet',
        loyaltyRewards: 'Loyalty Rewards',
        staffPayroll: 'Staff Payroll',
        doubleEntryAccounting: 'Double Entry Accounting',
        deliveryChallan: 'Delivery Challan',
        themeCustomization: 'Theme Customization',
        manageShortcuts: '+ Manage Shortcuts',
        salesPerformance: 'Sales Performance',
        financeDistribution: 'Finance Distribution',
        addMoney: 'Add Money',
        betaClub: 'BETA Club',
        tradingDocs: 'Trading Docs',

        tabProfile: 'Org Profile',
        tabGeneral: 'General',
        tabTransaction: 'Transaction',
        tabPrint: 'Print',
        tabGst: 'Taxes & GST',
        tabParty: 'Contacts',
        tabAccounting: 'Accounting',
        tabPayment: 'Payment',
        tabFinPro: 'FIN-PRO',
        tabBetaClub: 'Beta Club',

        applicationCore: 'Application Core',
        securityPasscode: 'Security Passcode',
        securityPasscodeDesc: 'Validate auth tokens before destructive operations.',
        preventNegativeInventory: 'Prevent Negative Inventory',
        preventNegativeInventoryDesc: 'Restrict invoicing items when stock level <= 0.',
        lockContactGeneration: 'Lock Contact Generation',
        lockContactGenerationDesc: 'Prevent new customer/supplier records within standard transaction forms.',
        operationalFeatures: 'Operational Features',
        activateDeliveryChallans: 'Activate Delivery Challans',
        reverseGoodsLogic: 'Reverse Goods Logic',
        displayAmount: 'Display Amount',
        warehousing: 'Warehousing',
        godownLinks: 'Godown Links',
        integrity: 'Integrity & Security',
        autoBackup: 'Auto Backup',
        auditTrail: 'Audit Trail',
        preferences: 'Preferences',
        darkMode: 'Dark Mode',
        darkModeDesc: 'Use a dark theme for the application interface.',
        language: 'Language',
        systemLanguageDesc: 'System localization language',
        notifications: 'Notifications',
        pushNotifications: 'Push Notifications',
        emailDigest: 'Email Digest',
        privacySecurity: 'Privacy & Security',
        publicProfile: 'Public Profile',
        twoFactor: 'Two-Factor Authentication',
        dataSharing: 'Data & Analytics'
    },
    'HI-IN': {
        books: 'बुक्स (Books)',
        payments: 'भुगतान (Payments)',
        social: 'सोशल (Social)',

        dashboard: 'डैशबोर्ड (Dashboard)',
        generateInvoice: '+ नया बिल बनाएं',
        finance: 'वित्त (Finance)',
        accounting: 'लेखांकन (Accounting)',
        expenses: 'खर्चे (Expenses)',
        tax: 'कर एवं टैक्स (Tax)',
        sales: 'बिक्री (Sales)',
        salesInvoice: 'बिक्री बिल',
        customers: 'ग्राहक (Customers)',
        purchases: 'खरीद (Purchases)',
        purchaseInvoice: 'खरीद बिल',
        suppliers: 'आपूर्तिकर्ता (Suppliers)',
        inventory: 'इन्वेंटरी और स्टॉक',
        products: 'उत्पाद (Products)',
        stockItems: 'स्टॉक आइटम',
        warehouses: 'गोदाम (Godowns)',
        hr: 'एचआर और कर्मचारी',
        staff: 'कर्मचारी (Staff)',
        attendance: 'उपस्थिति (Attendance)',
        payroll: 'वेतन (Payroll)',
        posBilling: 'पीओएस बिलिंग (POS)',
        reports: 'रिपोर्ट (Reports)',
        barcodeGen: 'बारकोड जनरेटर',
        marketing: 'मार्केटिंग एवं प्रचार',
        settings: 'सेटिंग्स (Settings)',
        helpSupport: 'सहायता एवं सपोर्ट',
        customization: 'कस्टमाइज़ेशन',
        advancedEngineConfig: 'उन्नत इंजन कॉन्फ़िगरेशन',
        back: 'वापस जाएं',
        deployConfig: 'कॉन्फ़िग सहेजें (DEPLOY)',
        storage: 'स्टोरेज (Storage)',
        referEarn: 'रेफर करें और कमाएं',
        managePlan: 'प्लान प्रबंधित करें',
        people: 'लोग (People)',
        wallet: 'वॉलेट (Wallet)',
        transaction: 'लेन-देन (Transaction)',
        segregation: 'पृथक्करण (Segregation)',
        splitCollect: 'स्प्लिट और कलेक्ट',
        planner: 'प्लानर (Planner)',
        rewardsOffers: 'पुरस्कार और ऑफ़र',
        rewardsSubtitle: 'विशेष प्लेटफॉर्म सौदे, छूट और प्रीमियम टियर अनलॉक करें।',
        activeRewardsPlan: 'सक्रिय पुरस्कार योजना',
        growBusinessPerks: 'अपना व्यवसाय बढ़ाएं, प्रीमियम लाभ प्राप्त करें',
        rewardsDescription: 'लॉयल्टी पॉइंट हासिल करने और डिस्काउंट अनलॉक करने के लिए लगातार मील के पत्थर पूरे करें और लेन-देन करें।',
        totalWalletPoints: 'कुल वॉलेट अंक',
        convertToWallet: 'वॉलेट में बदलें',
        exclusiveOffersBoosters: 'विशेष ऑफ़र और बूस्टर',
        updatedHourly: 'हर घंटे अपडेट',
        starterWalletReward: 'स्टार्टर वॉलेट लोड पुरस्कार',
        silverWalletReward: 'सिल्वर वॉलेट लोड पुरस्कार',
        goldWalletReward: 'गोल्ड वॉलेट लोड पुरस्कार',
        platinumWalletReward: 'प्लेटिनम वॉलेट लोड पुरस्कार',
        loadWalletNow: 'अभी वॉलेट लोड करें →',
        businessOverview: 'व्यवसाय अवलोकन (Overview)',
        monitorPerformance: 'अपने उद्यम के प्रदर्शन और संचालन की निगरानी करें।',
        customise: 'कस्टमाइज़ करें',
        totalSalesRevenue: 'कुल बिक्री राजस्व',
        totalPurchases: 'कुल खरीद',
        totalExpenses: 'कुल खर्चे',
        estNetProfit: 'अनुमानित शुद्ध लाभ',
        quickActionCenter: 'त्वरित कार्रवाई केंद्र (Quick Actions)',
        newInvoice: 'नया बिल',
        salesOrders: 'बिक्री ऑर्डर',
        addProduct: 'उत्पाद जोड़ें',
        addExpense: 'खर्चा जोड़ें',
        addCustomer: 'ग्राहक जोड़ें',
        newPurchasePo: 'नया खरीद पीओ',
        staffClaim: 'कर्मचारी दावा',
        onboardStaff: 'स्टाफ जोड़ें',
        gstRecords: 'जीएसटी रिकॉर्ड',
        marketingHub: 'मार्केटिंग हब',
        caAuditHub: 'फिन-प्रो ऑडिट हब',
        purchaseBills: 'खरीद बिल',
        newPurchaseBill: 'नया खरीद बिल',
        purchaseReturns: 'खरीद वापसी',
        newPurchaseReturn: 'नई खरीद वापसी',
        salesReturns: 'बिक्री वापसी',
        stockManagement: 'स्टॉक प्रबंधन',
        godownWarehouse: 'गोदाम / वेयरहाउस',
        barcodeGenerator: 'बारकोड जनरेटर',
        paymentsLedger: 'भुगतान बही',
        companyWallet: 'कंपनी वॉलेट',
        loyaltyRewards: 'पुरस्कार और रिवॉर्ड',
        staffPayroll: 'कर्मचारी वेतन',
        doubleEntryAccounting: 'डबल एंट्री अकाउंटिंग',
        deliveryChallan: 'डिलीवरी चालान',
        themeCustomization: 'थीम कस्टमाइज़ेशन',
        manageShortcuts: '+ शॉर्टकट प्रबंधित करें',
        salesPerformance: 'बिक्री प्रदर्शन',
        financeDistribution: 'वित्त वितरण',
        addMoney: '+ पैसे जोड़ें',
        betaClub: 'बीटा क्लब',
        tradingDocs: 'ट्रेडिंग दस्तावेज',

        tabProfile: 'फर्म प्रोफ़ाइल',
        tabGeneral: 'सामान्य सेटिंग्स',
        tabTransaction: 'लेन-देन नियम',
        tabPrint: 'प्रिंट सेटिंग्स',
        tabGst: 'कर एवं जीएसटी',
        tabParty: 'संपर्क (CRM)',
        tabAccounting: 'लेखांकन (Accounting)',
        tabPayment: 'भुगतान (Payments)',
        tabFinPro: 'फिन-प्रो (FIN-PRO)',
        tabBetaClub: 'बीटा क्लब',

        applicationCore: 'एप्लिकेशन कोर (Core)',
        securityPasscode: 'सुरक्षा पासकोड',
        securityPasscodeDesc: 'हटाने या बदलाव से पहले सुरक्षा पासकोड मांगें।',
        preventNegativeInventory: 'ऋणात्मक स्टॉक रोकें',
        preventNegativeInventoryDesc: 'स्टॉक 0 या कम होने पर बिलिंग रोकें।',
        lockContactGeneration: 'नया संपर्क निर्माण लॉक करें',
        lockContactGenerationDesc: 'बिलिंग फॉर्म से नया ग्राहक/सप्लायर जोड़ने पर रोक लगाएं।',
        operationalFeatures: 'परिचालन सुविधाएं',
        activateDeliveryChallans: 'डिलीवरी चालान चालू करें',
        reverseGoodsLogic: 'रिवर्स गुड्स लॉजिक',
        displayAmount: 'राशि दिखाएं',
        warehousing: 'गोदाम एवं वेयरहाउस',
        godownLinks: 'गोदाम लिंक (Godown Links)',
        integrity: 'सुरक्षा एवं बैकअप',
        autoBackup: 'ऑटो बैकअप',
        auditTrail: 'ऑडिट ट्रेल (गतिविधि रिकॉर्ड)',
        preferences: 'प्राथमिकताएं (Preferences)',
        darkMode: 'डार्क मोड (Dark Mode)',
        darkModeDesc: 'एप्लिकेशन इंटरफेस के लिए डार्क थीम का उपयोग करें।',
        language: 'भाषा (Language)',
        systemLanguageDesc: 'प्रणाली स्थानीयकरण भाषा',
        notifications: 'सूचनाएं (Notifications)',
        pushNotifications: 'पुश सूचनाएं',
        emailDigest: 'साप्ताहिक ईमेल सारांश',
        privacySecurity: 'गोपनीयता और सुरक्षा',
        publicProfile: 'सार्वजनिक प्रोफ़ाइल',
        twoFactor: 'दो-चरणीय प्रमाणीकरण (2FA)',
        dataSharing: 'डेटा और विश्लेषण'
    },
    'TE-IN': {
        books: 'బుక్స్ (Books)',
        payments: 'చెల్లింపులు (Payments)',
        social: 'సోషల్ (Social)',

        dashboard: 'డాష్‌బోర్డ్ (Dashboard)',
        generateInvoice: '+ కొత్త ఇన్వాయిస్',
        finance: 'ఫైనాన్స్ (Finance)',
        accounting: 'అకౌంటింగ్',
        expenses: 'ఖర్చులు (Expenses)',
        tax: 'పన్ను & జిఎస్‌టి (Tax)',
        sales: 'సేల్స్ (Sales)',
        salesInvoice: 'సేల్స్ ఇన్వాయిస్',
        customers: 'వినియోగదారులు',
        purchases: 'కొనుగోళ్లు (Purchases)',
        purchaseInvoice: 'కొనుగోలు బిల్లు',
        suppliers: 'సరఫరాదారులు',
        inventory: 'ఇన్వెంటరీ & స్టాక్',
        products: 'ఉత్పత్తులు (Products)',
        stockItems: 'స్టాక్ ఐటమ్స్',
        warehouses: 'గోదాములు (Godowns)',
        hr: 'హెచ్.ఆర్ & సిబ్బంది (HR)',
        staff: 'సిబ్బంది (Staff)',
        attendance: 'హాజరు (Attendance)',
        payroll: 'పేరోల్ (Payroll)',
        posBilling: 'పిఒఎస్ బిల్లింగ్ (POS)',
        reports: 'నివేదికలు (Reports)',
        barcodeGen: 'బార్‌కోడ్ జనరేటర్',
        marketing: 'మార్కెటింగ్',
        settings: 'సెట్టింగ్‌లు (Settings)',
        helpSupport: 'సహాయం & మద్దతు',
        customization: 'కస్టమైజేషన్',
        advancedEngineConfig: 'అడ్వాన్స్‌డ్ ఇంజిన్ కాన్ఫిగరేషన్',
        back: 'వెనుకకు (BACK)',
        deployConfig: 'కాన్ఫిగర్ వర్తింపజేయి (DEPLOY)',
        storage: 'స్టోరేజ్ (Storage)',
        referEarn: 'రెఫర్ & సంపాదించండి',
        managePlan: 'ప్లాన్ నిర్వహించండి',
        people: 'ప్రజలు (People)',
        wallet: 'వాలెట్ (Wallet)',
        transaction: 'లావాదేవీ (Transaction)',
        segregation: 'పృథక్కరణ',
        splitCollect: 'స్ప్లిట్ & కలెక్ట్',
        planner: 'ప్లానర్ (Planner)',
        rewardsOffers: 'రివార్డులు & ఆఫర్లు',
        rewardsSubtitle: 'ప్రత్యేక ఆఫర్లు, డిస్కౌంట్లు మరియు ప్రీమియం అన్‌లాక్‌లను పొందండి.',
        activeRewardsPlan: 'యాక్టివ్ రివార్డ్స్ ప్లాన్',
        growBusinessPerks: 'మీ వ్యాపారాన్ని పెంచుకోండి, రివార్డులు పొందండి',
        rewardsDescription: 'పాయింట్లను సాధించి రాయితీలను అన్‌లాక్ చేయడానికి నిరంతరం లావాదేవీలు నిర్వహించండి.',
        totalWalletPoints: 'మొత్తం వాలెట్ పాయింట్లు',
        convertToWallet: 'వాలెట్‌కి మార్చండి',
        exclusiveOffersBoosters: 'ప్రత్యేక ఆఫర్లు & బూస్టర్లు',
        updatedHourly: 'ప్రతి గంటకు నవీకరించబడుతుంది',
        starterWalletReward: 'స్టార్టర్ వాలెట్ లోడ్ రివార్డ్',
        silverWalletReward: 'సిల్వర్ వాలెట్ లోడ్ రివార్డ్',
        goldWalletReward: 'గోల్డ్ వాలెట్ లోడ్ రివార్డ్',
        platinumWalletReward: 'ప్లాటినం వాలెట్ లోడ్ రివార్డ్',
        loadWalletNow: 'ఇప్పుడే వాలెట్ లోడ్ చేయండి →',
        businessOverview: 'వ్యాపార అవలోకనం',
        monitorPerformance: 'మీ సంస్థ పనితీరు మరియు కార్యకలాపాలను పర్యవేక్షించండి.',
        customise: 'కస్టమైజ్',
        totalSalesRevenue: 'మొత్తం అమ్మకాల ఆదాయం',
        totalPurchases: 'మొత్తం కొనుగోళ్లు',
        totalExpenses: 'మొత్తం ఖర్చులు',
        estNetProfit: 'అంచనా వేసిన నికర లాభం',
        quickActionCenter: 'త్వరిత చర్యల కేంద్రం',
        newInvoice: 'కొత్త ఇన్వాయిస్',
        salesOrders: 'సేల్స్ ఆర్డర్లు',
        addProduct: 'ఉత్పత్తి జోడించండి',
        addExpense: 'ఖర్చు జోడించండి',
        addCustomer: 'కస్టమర్ జోడించండి',
        newPurchasePo: 'కొత్త కొనుగోలు ఆర్డర్',
        staffClaim: 'సిబ్బంది క్లెయిమ్',
        onboardStaff: 'సిబ్బంది చేరిక',
        gstRecords: 'జీఎస్టీ రికార్డులు',
        marketingHub: 'మార్కెటింగ్ హబ్',
        caAuditHub: 'ఫిన్-ప్రో ఆడిట్ హబ్',
        purchaseBills: 'కొనుగోలు బిల్లులు',
        newPurchaseBill: 'కొత్త కొనుగోలు బిల్లు',
        purchaseReturns: 'కొనుగోలు రిటర్న్స్',
        newPurchaseReturn: 'కొత్త కొనుగోలు రిటర్న్',
        salesReturns: 'అమ్మకాల రిటర్న్స్',
        stockManagement: 'స్టాక్ నిర్వహణ',
        godownWarehouse: 'గోదాము/వేర్‌హౌస్',
        barcodeGenerator: 'బార్‌కోడ్ జనరేటర్',
        paymentsLedger: 'చెల్లింపుల లెడ్జర్',
        companyWallet: 'కంపెనీ వాలెట్',
        loyaltyRewards: 'రివార్డులు',
        staffPayroll: 'సిబ్బంది పేరోల్',
        doubleEntryAccounting: 'డబుల్ ఎంట్రీ అకౌంటింగ్',
        deliveryChallan: 'డెలివరీ చలాన్',
        themeCustomization: 'థీమ్ కస్టమైజేషన్',
        manageShortcuts: '+ షార్ట్‌కట్‌లను నిర్వహించండి',
        salesPerformance: 'అమ్మకాల పనితీరు',
        financeDistribution: 'ఫైనాన్స్ పంపిణీ',
        addMoney: '+ డబ్బు జోడించండి',
        betaClub: 'బీటా క్లబ్',
        tradingDocs: 'ట్రేడింగ్ పత్రాలు',

        tabProfile: 'సంస్థ ప్రొఫైల్',
        tabGeneral: 'సాధారణ సెట్టింగ్‌లు',
        tabTransaction: 'లావాదేవీల నియమాలు',
        tabPrint: 'ప్రింట్ సెట్టింగ్‌లు',
        tabGst: 'పన్నులు & GST',
        tabParty: 'కాంటాక్ట్స్ (CRM)',
        tabAccounting: 'అకౌంటింగ్',
        tabPayment: 'చెల్లింపులు',
        tabFinPro: 'ఫిన్-ప్రో',
        tabBetaClub: 'బీటా క్లబ్',

        applicationCore: 'అప్లికేషన్ కోర్',
        securityPasscode: 'సెక్యూరిటీ పాస్‌కోడ్',
        securityPasscodeDesc: 'హానికరమైన ఆపరేషన్లకు ముందు ప్రామాణీకరించండి.',
        preventNegativeInventory: 'నెగటివ్ ఇన్వెంటరీ నిరోధించండి',
        preventNegativeInventoryDesc: 'స్టాక్ సున్నా లేదా అంతకంటే తక్కువగా ఉన్నప్పుడు బిల్లింగ్ పరిమితం చేయండి.',
        lockContactGeneration: 'కాంటాక్ట్ జనరేషన్ లాక్ చేయండి',
        lockContactGenerationDesc: 'స్టాండర్డ్ ఫారమ్‌లలో కొత్త పరిచయాల సృష్టిని నిరోధించండి.',
        operationalFeatures: 'ఆపరేషనల్ ఫీచర్లు',
        activateDeliveryChallans: 'డెలివరీ చలాన్లను ప్రారంభించండి',
        reverseGoodsLogic: 'రివర్స్ గూడ్స్ లాజిక్',
        displayAmount: 'మొత్తాన్ని చూపించు',
        warehousing: 'వేర్‌హౌసింగ్ & గోదాములు',
        godownLinks: 'గోదాము లింకులు',
        integrity: 'భద్రత & ఆడిట్',
        autoBackup: 'ఆటో బ్యాకప్',
        auditTrail: 'ఆడిట్ ట్రెయిల్',
        preferences: 'ప్రాధాన్యతలు (Preferences)',
        darkMode: 'డార్క్ మోడ్ (Dark Mode)',
        darkModeDesc: 'అప్లికేషన్ కోసం డార్క్ థీమ్‌ను ఉపయోగించండి.',
        language: 'భాష (Language)',
        systemLanguageDesc: 'సిస్టమ్ లొకలైజేషన్ భాష',
        notifications: 'నోటిఫికేషన్లు',
        pushNotifications: 'పుష్ నోటిఫికేషన్లు',
        emailDigest: 'ఈమెయిల్ సారాంశం',
        privacySecurity: 'గోప్యత & భద్రత',
        publicProfile: 'పబ్లిక్ ప్రొఫైల్',
        twoFactor: 'రెండు-దశల ప్రామాణీకరణ (2FA)',
        dataSharing: 'డేటా & విశ్లేషణలు'
    },
    'TA-IN': {
        books: 'புத்தகங்கள் (Books)',
        payments: 'செலுத்துதல்கள் (Payments)',
        social: 'சமூக (Social)',

        dashboard: 'டேஷ்போர்டு (Dashboard)',
        generateInvoice: '+ புதிய இன்வாய்ஸ் உருவாக்கு',
        finance: 'நிதி (Finance)',
        accounting: 'கணக்கியல் (Accounting)',
        expenses: 'செலவுகள் (Expenses)',
        tax: 'வரி & ஜிஎஸ்டி (Tax)',
        sales: 'விற்பனை (Sales)',
        salesInvoice: 'விற்பனை பில்',
        customers: 'வாடிக்கையாளர்கள்',
        purchases: 'கொள்முதல் (Purchases)',
        purchaseInvoice: 'கொள்முதல் பில்',
        suppliers: 'விநியோகஸ்தர்கள்',
        inventory: 'சரக்கு & இருப்பு (Inventory)',
        products: 'சரக்கு பொருட்கள்',
        stockItems: 'இருப்பு பொருட்கள்',
        warehouses: 'கிடங்குகள் (Godowns)',
        hr: 'ஊழியர்கள் மேலாண்மை (HR)',
        staff: 'ஊழியர்கள்',
        attendance: 'வருகை',
        payroll: 'சம்பளம்',
        posBilling: 'POS பில்லிங்',
        reports: 'அறிக்கைகள் (Reports)',
        barcodeGen: 'பார்கோடு ஜெனரேட்டர்',
        marketing: 'சந்தைப்படுத்தல்',
        settings: 'அமைப்புகள் (Settings)',
        helpSupport: 'உதவி & ஆதரவு',
        customization: 'தனிப்பயனாக்கம்',
        advancedEngineConfig: 'மேம்பட்ட என்ஜின் அமைப்பு',
        back: 'பின்னால் (BACK)',
        deployConfig: 'சேமிக்க (DEPLOY)',
        storage: 'சேமிப்பகம் (Storage)',
        referEarn: 'பரிந்துரைத்து சம்பாதிக்கவும்',
        managePlan: 'திட்டத்தை நிர்வகிக்கவும்',
        people: 'மக்கள் (People)',
        wallet: 'வாலட் (Wallet)',
        transaction: 'பரிவர்த்தனை (Transaction)',
        segregation: 'பிரிப்பு (Segregation)',
        splitCollect: 'பிரித்து சேகரி',
        planner: 'திட்டமிடுபவர் (Planner)',
        rewardsOffers: 'பரிசுகள் & சலுகைகள்',
        rewardsSubtitle: 'சிறப்பு சலுகைகள், தள்ளுபடிகள் மற்றும் பிரீமியம் நன்மைகளைப் பெறுங்கள்.',
        activeRewardsPlan: 'செயலில் உள்ள வெகுமதி திட்டம்',
        growBusinessPerks: 'உங்கள் வணிகத்தை வளர்க்கவும், நன்மைகளை பெறவும்',
        rewardsDescription: 'புள்ளிகளைப் பெற மற்றும் தள்ளுபடிகளைத் திறக்க தொடர்ந்து பரிவர்த்தனை செய்யுங்கள்.',
        totalWalletPoints: 'மொத்த வாலட் புள்ளிகள்',
        convertToWallet: 'வாலட்டிற்கு மாற்றவும்',
        exclusiveOffersBoosters: 'பிரத்யேக சலுகைகள் & பூஸ்டர்கள்',
        updatedHourly: 'மணிநேரத்திற்கு புதுப்பிக்கப்படும்',
        starterWalletReward: 'ஸ்டார்ட்டர் வாலட் லோட் சலுகை',
        silverWalletReward: 'சில்வர் வாலட் லோட் சலுகை',
        goldWalletReward: 'கோல்ட் வாலட் லோட் சலுகை',
        platinumWalletReward: 'பிளாட்டினம் வாலட் லோட் சலுகை',
        loadWalletNow: 'இப்போதே வாலட்டை நிரப்புக →',
        businessOverview: 'வணிக மேலோட்டம்',
        monitorPerformance: 'உங்கள் நிறுவனத்தின் செயல்பாடு மற்றும் செயல்பாடுகளைக் கண்காணிக்கவும்.',
        customise: 'தனிப்பயனாக்கு',
        totalSalesRevenue: 'மொத்த விற்பனை வருவாய்',
        totalPurchases: 'மொத்த கொள்முதல்',
        totalExpenses: 'மொத்த செலவுகள்',
        estNetProfit: 'மதிப்பிடப்பட்ட நிகர லாபம்',
        quickActionCenter: 'விரைவு நடவடிக்கை மையம்',
        newInvoice: 'புதிய இன்வாய்ஸ்',
        salesOrders: 'விற்பனை ஆர்டர்கள்',
        addProduct: 'பொருள் சேர்',
        addExpense: 'செலவு சேர்',
        addCustomer: 'வாடிக்கையாளர் சேர்',
        newPurchasePo: 'புதிய கொள்முதல் ஆர்டர்',
        staffClaim: 'ஊழியர் கோரிக்கை',
        onboardStaff: 'ஊழியர் சேர்ப்பு',
        gstRecords: 'ஜிஎஸ்டி பதிவுகள்',
        marketingHub: 'மார்க்கெட்டிங் மையம்',
        caAuditHub: 'பின்-ப்ரோ தணிக்கை மையம்',
        purchaseBills: 'கொள்முதல் பில்கள்',
        newPurchaseBill: 'புதிய கொள்முதல் பில்',
        purchaseReturns: 'கொள்முதல் திருப்பங்கள்',
        newPurchaseReturn: 'புதிய கொள்முதல் திருப்பம்',
        salesReturns: 'விற்பனை திருப்பங்கள்',
        stockManagement: 'இருப்பு மேலாண்மை',
        godownWarehouse: 'கிடங்கு/சேமிப்பகம்',
        barcodeGenerator: 'பார்கோடு ஜெனரேட்டர்',
        paymentsLedger: 'செலுத்துதல் பேரேடு',
        companyWallet: 'நிறுவன வாலட்',
        loyaltyRewards: 'வெகுமதிகள்',
        staffPayroll: 'ஊழியர் சம்பளம்',
        doubleEntryAccounting: 'இரட்டைப் பதிவு கணக்கியல்',
        deliveryChallan: 'டெலிவரி சலான்',
        themeCustomization: 'அமைப்பு தனிப்பயனாக்கம்',
        manageShortcuts: '+ குறுக்குவழிகள் மேலாண்மை',
        salesPerformance: 'விற்பனை செயல்பாடு',
        financeDistribution: 'நிதி விநியோகம்',
        addMoney: '+ பணம் சேர்க்க',
        betaClub: 'பீட்டா கிளப்',
        tradingDocs: 'வர்த்தக ஆவணங்கள்',

        tabProfile: 'நிறுவன சுயவிவரம்',
        tabGeneral: 'பொது அமைப்புகள்',
        tabTransaction: 'பரிவர்த்தனை விதிகள்',
        tabPrint: 'அச்சு அமைப்புகள்',
        tabGst: 'வரிகள் & ஜிஎஸ்டி',
        tabParty: 'தொடர்புகள் (CRM)',
        tabAccounting: 'கணக்கியல்',
        tabPayment: 'செலுத்துதல்கள்',
        tabFinPro: 'பின்-ப்ரோ',
        tabBetaClub: 'பீட்டா கிளப்',

        applicationCore: 'பயன்பாட்டு மையம்',
        securityPasscode: 'பாதுகாப்பு பாஸ்கோடு',
        securityPasscodeDesc: 'முக்கியமான செயல்களுக்கு முன் சரிபார்க்கவும்.',
        preventNegativeInventory: 'எதிர்மறை இருப்பைத் தவிர்',
        preventNegativeInventoryDesc: 'இருப்பு 0 ஆக இருக்கும்போது பில்லிங்கைக் கட்டுப்படுத்துங்கள்.',
        lockContactGeneration: 'புதிய தொடர்புகளை பூட்டு',
        operationalFeatures: 'இயக்க அம்சங்கள்',
        activateDeliveryChallans: 'டெலிவரி சலான்களை இயக்கு',
        reverseGoodsLogic: 'தலைகீழ் பொருட்கள் தர்க்கம்',
        displayAmount: 'தொகையைக் காட்டு',
        warehousing: 'கிடங்குகள்',
        godownLinks: 'கிடங்கு இணைப்புகள்',
        integrity: 'பாதுகாப்பு & தணிக்கை',
        autoBackup: 'தானியங்கி பேக்கப்',
        auditTrail: 'தணிக்கைப் பாதை',
        preferences: 'விருப்பத்தேர்வுகள் (Preferences)',
        darkMode: 'டார்க் மோட் (Dark Mode)',
        darkModeDesc: 'பயன்பாட்டிற்கு இருண்ட தீமைப் பயன்படுத்தவும்.',
        language: 'மொழி (Language)',
        systemLanguageDesc: 'அமைப்பு மொழி அமைப்புகள்',
        notifications: 'அறிவிப்புகள்',
        pushNotifications: 'புஷ் அறிவிப்புகள்',
        emailDigest: 'மின்னஞ்சல் சுருக்கம்',
        privacySecurity: 'தனியுரிமை & பாதுகாப்பு',
        publicProfile: 'பொது சுயவிவரம்',
        twoFactor: 'இரு காரணி அங்கீகாரம்',
        dataSharing: 'தரவு பகுப்பாய்வு'
    },
    'MR-IN': {
        books: 'बुक्स (Books)',
        payments: 'पेमेंट्स (Payments)',
        social: 'सोशल (Social)',

        dashboard: 'डॅशबोर्ड (Dashboard)',
        generateInvoice: '+ नवीन बिल बनवा',
        finance: 'वित्त (Finance)',
        accounting: 'अकाउंटिंग',
        expenses: 'खर्च (Expenses)',
        tax: 'कर व जीएसटी (Tax)',
        sales: 'विक्री (Sales)',
        salesInvoice: 'विक्री बिल',
        customers: 'ग्राहक (Customers)',
        purchases: 'खरेदी (Purchases)',
        purchaseInvoice: 'खरेदी बिल',
        suppliers: 'पुरवठादार (Suppliers)',
        inventory: 'इन्व्हेंटरी व साठा',
        products: 'उत्पादने (Products)',
        stockItems: 'स्टॉक आयटम्स',
        warehouses: 'गोदाम (Godowns)',
        hr: 'एचआर व कर्मचारी',
        staff: 'कर्मचारी (Staff)',
        attendance: 'हजेरी (Attendance)',
        payroll: 'पेरोल (Payroll)',
        posBilling: 'POS बिलिंग',
        reports: 'अहवाल (Reports)',
        barcodeGen: 'बारकोड जनरेटर',
        marketing: 'मार्केटिंग',
        settings: 'सेटिंग्ज (Settings)',
        helpSupport: 'मदत व पाठिंबा',
        customization: 'कस्टमायझेशन',
        advancedEngineConfig: 'प्रगत इंजिन कॉन्फिगरेशन',
        back: 'मागे (BACK)',
        deployConfig: 'कॉन्फिग लागू करा (DEPLOY)',
        storage: 'स्टोरेज (Storage)',
        referEarn: 'रेफर करा व कमवा',
        managePlan: 'प्लॅन व्यवस्थापित करा',
        people: 'लोक (People)',
        wallet: 'वॉलेट (Wallet)',
        transaction: 'व्यवहार (Transaction)',
        segregation: 'विभक्तीकरण',
        splitCollect: 'स्प्लिट आणि कलेक्ट',
        planner: 'प्लॅनर (Planner)',
        rewardsOffers: 'बक्षिसे व ऑफर्स',
        addMoney: '+ पैसे जोडा',
        betaClub: 'बीटा क्लब',
        tradingDocs: 'ट्रेडिंग दस्तऐवज',

        tabProfile: 'संस्था प्रोफाइल',
        tabGeneral: 'सामान्य सेटिंग्स',
        tabTransaction: 'व्यवहार नियम',
        tabPrint: 'प्रिंट सेटिंग्स',
        tabGst: 'कर व जीएसटी',
        tabParty: 'संपर्क (CRM)',
        tabAccounting: 'अकाउंटिंग',
        tabPayment: 'पेमेंट',
        tabFinPro: 'फिन-प्रो',
        tabBetaClub: 'बीटा क्लब',

        applicationCore: 'ॲप्लिकेशन कोर',
        securityPasscode: 'सुरक्षा पासकोड',
        securityPasscodeDesc: 'महत्वाच्या क्रियेपूर्वी सुरक्षा पासकोड तपासा.',
        preventNegativeInventory: 'नकारात्मक स्टॉक रोखा',
        preventNegativeInventoryDesc: 'साठा ० असताना बिलिंग रोखा.',
        lockContactGeneration: 'नवीन संपर्क निर्मिती लॉक करा',
        operationalFeatures: 'ऑपरेशनल वैशिष्ट्ये',
        activateDeliveryChallans: 'डिलिव्हरी चालान सुरू करा',
        reverseGoodsLogic: 'रिव्हर्स गुड्स लॉजिक',
        displayAmount: 'रक्कम दाखवा',
        warehousing: 'गोदाम व्यवस्थापन',
        godownLinks: 'गोदाम लिंक्स',
        integrity: 'सुरक्षा व बॅकअप',
        autoBackup: 'ऑटो बॅकअप',
        auditTrail: 'ऑडिट ट्रेल',
        preferences: 'पसंती (Preferences)',
        darkMode: 'डार्क मोड (Dark Mode)',
        darkModeDesc: 'इंटरफेससाठी डार्क थीम वापरा.',
        language: 'भाषा (Language)',
        systemLanguageDesc: 'प्रणाली भाषा',
        notifications: 'सूचना',
        pushNotifications: 'पुश सूचना',
        emailDigest: 'ईमेल सारांश',
        privacySecurity: 'गोपनीयता व सुरक्षा',
        publicProfile: 'सार्वजनिक प्रोफाइल',
        twoFactor: 'दुहेरी प्रमाणीकरण (2FA)',
        dataSharing: 'डेटा ॲनालिटिक्स'
    },
    'GU-IN': {
        books: 'બુક્સ (Books)',
        payments: 'ચુકવણીઓ (Payments)',
        social: 'સોશિયલ (Social)',

        dashboard: 'ડેશબોર્ડ (Dashboard)',
        generateInvoice: '+ નવું બિલ બનાવો',
        finance: 'નાણાકીય (Finance)',
        accounting: 'એકાઉન્ટિંગ',
        expenses: 'ખર્ચ (Expenses)',
        tax: 'ટેક્સ અને જીએસટી (Tax)',
        sales: 'વેચાણ (Sales)',
        salesInvoice: 'વેચાણ બિલ',
        customers: 'ગ્રાહકો (Customers)',
        purchases: 'ખરીદી (Purchases)',
        purchaseInvoice: 'ખરીદી બિલ',
        suppliers: 'સપ્લાયર્સ (Suppliers)',
        inventory: 'ઇન્વેન્ટરી સ્ટોક',
        products: 'પ્રોડક્ટ્સ (Products)',
        stockItems: 'સ્ટોક વસ્તુઓ',
        warehouses: 'ગોડાઉન (Godowns)',
        hr: 'એચઆર અને સ્ટાફ',
        staff: 'સ્ટાફ (Staff)',
        attendance: 'હાજરી (Attendance)',
        payroll: 'પગાર (Payroll)',
        posBilling: 'POS બિલિંગ',
        reports: 'રિપોર્ટ્સ (Reports)',
        barcodeGen: 'બારકોડ જનરેટર',
        marketing: 'માર્કેટિંગ',
        settings: 'સેટિંગ્સ (Settings)',
        helpSupport: 'મદદ અને સપોર્ટ',
        customization: 'કસ્ટમાઇઝેશન',
        advancedEngineConfig: 'એડવાન્સ્ડ એન્જિન કન્ફિગરેશન',
        back: 'પાછા (BACK)',
        deployConfig: 'કન્ફિગ સેટ કરો (DEPLOY)',
        storage: 'સ્ટોરેજ (Storage)',
        referEarn: 'રેફર કરો અને કમાઓ',
        managePlan: 'પ્લાન મેનેજ કરો',
        people: 'લોકો (People)',
        wallet: 'વોલેટ (Wallet)',
        transaction: 'વ્યવહાર (Transaction)',
        segregation: 'વર્ગીકરણ',
        splitCollect: 'સ્પ્લિટ અને કલેક્ટ',
        planner: 'પ્લાનર (Planner)',
        rewardsOffers: 'રિવોર્ડ્સ અને ઑફર્સ',
        addMoney: '+ પૈસા ઉમેરો',
        betaClub: 'બીટા ક્લબ',
        tradingDocs: 'ટ્રેડિંગ દસ્તાવેજો',

        tabProfile: 'સંસ્થા પ્રોફાઇલ',
        tabGeneral: 'સામાન્ય સેટિંગ્સ',
        tabTransaction: 'વ્યવહાર નિયમો',
        tabPrint: 'પ્રિન્ટ સેટિંગ્સ',
        tabGst: 'ટેક્સ અને GST',
        tabParty: 'સંપર્કો (CRM)',
        tabAccounting: 'એકાઉન્ટિંગ',
        tabPayment: 'ચુકવણીઓ',
        tabFinPro: 'ફિન-પ્રો',
        tabBetaClub: 'બીટા ક્લબ',

        applicationCore: 'એપ્લિકેશન કોર',
        securityPasscode: 'સુરક્ષા પાસકોડ',
        securityPasscodeDesc: 'મહત્વપૂર્ણ ક્રિયાઓ પહેલાં ચકાસણી કરો.',
        preventNegativeInventory: 'નેગેટિવ ઇન્વેન્ટરી અટકાવો',
        preventNegativeInventoryDesc: 'જ્યારે સ્ટોક ૦ હોય ત્યારે બિલિંગ મર્યાદિત કરો.',
        lockContactGeneration: 'નવા સંપર્ક બનાવટ લોક કરો',
        operationalFeatures: 'ઓપરેશનલ ફીચર્સ',
        activateDeliveryChallans: 'ડિલિવરી ચલણ સક્રિય કરો',
        reverseGoodsLogic: 'રિવર્સ ગુડ્સ લોજિક',
        displayAmount: 'રકમ દર્શાવો',
        warehousing: 'ગોડાઉન મેનેજમેન્ટ',
        godownLinks: 'ગોડાઉન લિંક્સ',
        integrity: 'સુરક્ષા અને બેકઅપ',
        autoBackup: 'ઓટો બેકઅપ',
        auditTrail: 'ઓડિટ ટ્રેઇલ',
        preferences: 'પસંદગીઓ (Preferences)',
        darkMode: 'ડાર્ક મોડ (Dark Mode)',
        darkModeDesc: 'ઇન્ટરફેસ માટે ડાર્ક થીમનો ઉપયોગ કરો.',
        language: 'ભાષા (Language)',
        systemLanguageDesc: 'સિસ્ટમ સ્થાનિકીકરણ ભાષા',
        notifications: 'નોટિફિકેશન્સ',
        pushNotifications: 'પુશ નોટિફિકેશન્સ',
        emailDigest: 'ઈમેઇલ સારાંશ',
        privacySecurity: 'ગોપનીયતા અને સુરક્ષા',
        publicProfile: 'પબ્લિક પ્રોફાઇલ',
        twoFactor: 'ટુ-ફેક્ટર ઓથેન્ટિકેશન (2FA)',
        dataSharing: 'ડેટા એનાલિટિક્સ'
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguageState] = useState(() => {
        if (typeof window !== 'undefined') {
            const stored = localStorage.getItem('cliks_language');
            if (stored) return stored;

            const storedConfigRaw = localStorage.getItem('cliks_business_config') || localStorage.getItem('cliks_active_config');
            if (storedConfigRaw) {
                try {
                    const parsed = JSON.parse(storedConfigRaw);
                    if (parsed && parsed.language) return parsed.language;
                } catch (e) {}
            }
        }
        return 'EN-US';
    });

    const setLanguage = useCallback((langCode) => {
        if (!langCode) return;
        setLanguageState(langCode);
        localStorage.setItem('cliks_language', langCode);

        if (typeof document !== 'undefined') {
            document.documentElement.setAttribute('lang', langCode);
        }

        try {
            const currentConfigRaw = localStorage.getItem('cliks_business_config') || '{}';
            const currentConfig = JSON.parse(currentConfigRaw);
            currentConfig.language = langCode;
            localStorage.setItem('cliks_business_config', JSON.stringify(currentConfig));
            localStorage.setItem('cliks_active_config', JSON.stringify(currentConfig));
        } catch (e) {}

        window.dispatchEvent(new CustomEvent('cliksConfigUpdated', { detail: { language: langCode } }));
    }, []);

    useEffect(() => {
        const handleSync = (e) => {
            let stored = localStorage.getItem('cliks_language');
            if (e && e.detail && e.detail.language) {
                stored = e.detail.language;
            }
            if (stored && stored !== language) {
                setLanguageState(stored);
            }
        };
        window.addEventListener('cliksConfigUpdated', handleSync);
        window.addEventListener('storage', handleSync);
        return () => {
            window.removeEventListener('cliksConfigUpdated', handleSync);
            window.removeEventListener('storage', handleSync);
        };
    }, [language]);

    const t = useCallback((key, fallback) => {
        const normKey = normalizeKey(key);
        const currentDict = translations[language] || translations['EN-US'];

        if (currentDict && currentDict[normKey]) {
            return currentDict[normKey];
        }
        if (currentDict && currentDict[key]) {
            return currentDict[key];
        }

        const defaultDict = translations['EN-US'];
        if (defaultDict && defaultDict[normKey]) {
            return defaultDict[normKey];
        }
        return fallback || key;
    }, [language]);

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, translations }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const ctx = useContext(LanguageContext);
    if (!ctx) {
        return {
            language: 'EN-US',
            setLanguage: () => {},
            t: (key, fallback) => {
                const normKey = normalizeKey(key);
                const defaultDict = translations['EN-US'];
                return defaultDict[normKey] || defaultDict[key] || fallback || key;
            },
            translations
        };
    }
    return ctx;
};
